### ISSUE TITLE
слишком сложно для ботоделов

### ISSUE THREAD

**Issue by AlekseyZz** [monochrome-js/monochrome#1]
помогите 🤙🤘👐🙏

**Comment by m-xz** [comment]
Добрый день! Скоро мы это исправим, добавив функцию `makeBot(token: string)`, которая будет создавать оптимального бота! Надеюсь, вы разберётесь, как получить токен вашего бота, ведь в программировании без испытаний никуда! 

Если вы жаждете большего, вы сможете также указать нужные команды вторым аргументом - это открывает огромные пути кастомизации вашего бота. Просто вводите нужные команды и проверяйте - есть ли ошибки. Если нет, поздравляю - вы теперь настоящий бот-дев!

**Comment by AlekseyZz** [comment]
спасибо 👩👨
